### ISSUE TITLE
Add leading zero to single digit folder names

### ISSUE THREAD

**Issue by sweenish** [microsoft/c9-python-getting-started#1]
I attempted to create a pull request since this is such a small change, but I was denied access. This is from a cloned repository.

My attempt to push: `git push --set-upstream origin rename-folders`
My push error is repeated here:
```
remote: Permission to microsoft/c9-python-getting-started.git denied to sweenish.
fatal: unable to access 'https://github.com/microsoft/c9-python-getting-started.git/': The requested URL returned error: 403
```

I am able to clone and push to my own GitHub repositories without issues.

**Comment by wlerin** [comment]
I literally laughed out loud when I saw this issue, because I opened the issues tab to say the exact same thing. However, it might be more complex than just renaming them: if there are any links to the content of those folders those will need to be fixed as well.

As for the push error, fork the repository, push your changes to that fork, then create a pull request here on GitHub.

**Comment by mycroft16** [comment]
> I literally laughed out loud when I saw this issue, because I opened the issues tab to say the exact same thing. However, it might be more complex than just renaming them: if there are any links to the content of those folders those will need to be fixed as well. Looks like the video series just links to the main repo, so that might not be a problem.
> 
> As for the push error, you'd need to either be added as a contributor to this repository, or fork it, clone that fork and make your changes, and then create a pull request on GitHub.

I literally opened the issue tab about 10 seconds after seeing this repo for the same reason. :D

**Comment by sweenish** [comment]
> I literally laughed out loud when I saw this issue, because I opened the issues tab to say the exact same thing. However, it might be more complex than just renaming them: if there are any links to the content of those folders those will need to be fixed as well. Looks like the video series just links to the main repo, so that might not be a problem.
> 
> As for the push error, you'd need to either be added as a contributor to this repository, or fork it, clone that fork and make your changes, and then create a pull request on GitHub.

I haven't watched the entire series yet, but as far as I've noticed the links are just to the main repository like you said. 

As for actually submitting the change, I'll follow your steps.
