### ISSUE TITLE
Tuples not described in Collections folder.

### ISSUE THREAD

**Issue by srishti-nema** [microsoft/c9-python-getting-started#25]
Tuples are immutable collections used to store heterogeneous data. This is one of the basic concepts described in detail in the Python documentation.

[Documentation](https://docs.python.org/3/library/stdtypes.html?#tuples)

**Comment by GeekTrainer** [comment]
Totally fair! It was a tough decision to leave this off, but unfortunately we only had so much time. We are going to cover tuples in a future course.
