### ISSUE TITLE
Python OOPs concepts

### ISSUE THREAD

**Issue by pyrate26** [microsoft/c9-python-getting-started#28]
The videos are awesome. Thank you so much.

Could you please add videos for OOPs concepts in Python as well.

Thank you.

**Comment by GeekTrainer** [comment]
Keep your eyes peeled for a future course! :-)

**Comment by StefanMoore** [comment]
I know this discussion is closed but is there an ETA on when the new videos will be on the site?

**Comment by GeekTrainer** [comment]
There isn't. We're planning on getting back into the studio in a month or so, and the release would occur after that. I'm not trying to be cagey, I just don't have the info to share :-)
