### ISSUE TITLE
Ch. 15 - Link to virtual environments points to Exceptions

### ISSUE THREAD

**Issue by vbrh-immalle** [microsoft/c9-python-getting-started#42]
In `README.md` of chapter 15 (packages) the link to *virtual environments* points to https://docs.python.org/3.7/library/exceptions.html instead.

https://github.com/microsoft/c9-python-getting-started/blame/master/15%20-%20Packages/README.md#L27

**Comment by profread** [comment]
Will check this out ?

**Comment by HeroicHitesh** [comment]
PR #56 resolves this issue. Let's see when it gets merged 😅
